server:
  port: 8080

spring:
  application:
    name: bsapi
  datasource:
    url: jdbc:postgresql://localhost:5432/bsdb
    username: bsdbu
    password: bsdbp2Pass&1!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
        jdbc:
          time-zone: UTC
    open-in-view: false
    # only for dev -- full auth in production
#renders this a security risk
  security:
    user:
      name: admin
      password: lsetga
jwt:
  secret: ${JWT_SECRET:bluestronTrainingBusinessSecretKeyForJWTSigning2024}
  expiration: 86400000 # 24 hours


management:
  endpoints:
    web:
      exposure:
        include: health,mappings,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
