server:
  port: 8080

spring:
  application:
    name: bsapi
  datasource:
    url: jdbc:postgresql://localhost:5432/bsdb
    username: bsdbu
    password: bsdbp2Pass&1!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
        jdbc:
          time-zone: UTC
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,mappings,info
  endpoint:
    health:
      show-details: when_authorized

jwt:
  secret: 3f9a7c2d8b1e4f6a9d0c5b7e2f8a1c3d6e9b4a7f0c2d5e8b1a3c6d9f2a7b0c4


logging:
  level:
    root: INFO
